[package]
name = "offsetcalculator"
version = "0.1.0"
edition = "2021"
authors = ["Lut99"]

[workspace]

[dependencies]
unicode-segmentation = "1.8.0"
hex = "0.4.3"
rustyline = "9.1.2"
signal-hook = "0.3.13"
parse-args = { git = "https://github.com/Lut99/parse-args", branch="main" }
